[folder]
title = 'Folder'
desc = 'A simple folder object with a title and description field.'

template = 'types/folder.html.j2'
schema = 'evie.content.schema.folder.IFolder'
klass = 'evie.content.schema.folder.Folder'

access_perm = ''
allowed_types = ['page']

[page]
title = 'Page'
desc = 'A simple page object with a title, description and text field.'

template = 'types/page.html.j2'
schema = 'evie.content.schema.page.IPage'
klass = 'evie.content.schema.page.Page'

access_perm = ''

[site]
title = 'Site'
desc = 'A site object.'

template = 'types/site.html.j2'
schema = 'evie.content.schema.site.ISite'
klass = 'evie.content.schema.site.Site'

access_perm = ''
