[folder]
title = 'Folder'
desc = 'A container object.'
template = 'types/folder.html.j2'
schema = '.types.folder.IFolder'
object_class = '.types.folder.Folder'


[page]
title = 'Page'
desc = 'A simple page object with a title, description and text field.'
template = 'types/page.html.j2'
schema = '.types.page.IPage'
object_class = '.types.page.Page'
